-- ============================================
-- PRESYRA - AI ATTENDANCE SYSTEM DATABASE
-- ============================================


-- ============================================
-- 1. TEACHERS TABLE
-- ============================================

CREATE TABLE teachers (
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT
);


-- ============================================
-- 2. STUDENTS TABLE
-- ============================================

CREATE TABLE students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    face_embedding JSONB,
    voice_embedding JSONB
);


-- ============================================
-- 3. SUBJECTS TABLE
-- ============================================

CREATE TABLE subjects (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code TEXT NOT NULL,
    name TEXT DEFAULT 'UNKNOWN',
    section TEXT DEFAULT 'N/A',
    teacher_id BIGINT
        REFERENCES teachers(teacher_id)
        ON DELETE SET NULL
);


-- ============================================
-- 4. SUBJECT-STUDENTS TABLE
-- Many-to-Many relationship
-- ============================================

CREATE TABLE subject_students (
    subject_id BIGINT
        REFERENCES subjects(subject_id)
        ON DELETE CASCADE,

    student_id BIGINT
        REFERENCES students(student_id)
        ON DELETE CASCADE,

    PRIMARY KEY (subject_id, student_id)
);


-- ============================================
-- 5. ATTENDANCE LOGS TABLE
-- ============================================

CREATE TABLE attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    timestamp TIMESTAMPTZ DEFAULT NOW(),

    subject_id BIGINT
        REFERENCES subjects(subject_id)
        ON DELETE CASCADE,

    student_id BIGINT
        REFERENCES students(student_id)
        ON DELETE CASCADE,

    is_present BOOLEAN DEFAULT TRUE
);

